import React, { useState, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { logoutUser } from '../auth/auth.slice';
import { Link } from 'react-router-dom';
import axios from 'axios';
import BridgeLoader from '../../components/BridgeLoader';
import BridgeIcon from '../../assets/Bridge.png';

/**
 * Company Dashboard Screen
 * Displays Company Profile details, operational stats, appointed Manager, 
 * Purchase Officer (PO) staff list, and RFQs generated by this company's POs.
 */
const CompanyPage = () => {
  const { user } = useSelector((state) => state.auth);
  const dispatch = useDispatch();

  const [dashboardData, setDashboardData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [activeTab, setActiveTab] = useState('overview');

  const handleLogout = () => {
    dispatch(logoutUser());
  };

  useEffect(() => {
    const fetchDashboard = async () => {
      try {
        const token = localStorage.getItem('token');
        const config = {
          headers: token ? { Authorization: `Bearer ${token}` } : {},
          withCredentials: true,
        };
        // Fetch dashboard data from api
        const response = await axios.get('http://localhost:3000/api/auth/company-dashboard', config);
        if (response.data.success) {
          setDashboardData(response.data);
        } else {
          setError(response.data.message || 'Failed to fetch dashboard data');
        }
      } catch (err) {
        console.error('Fetch dashboard error:', err);
        setError(err.response?.data?.message || 'Error connecting to the server');
      } finally {
        setLoading(false);
      }
    };

    fetchDashboard();
  }, []);

  if (loading) {
    return <BridgeLoader fullscreen message="Loading Company Console…" />;
  }

  if (error) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
        <div className="max-w-md w-full bg-white rounded-2xl border border-slate-200 p-6 shadow-sm text-center">
          <div className="w-12 h-12 bg-rose-50 border border-rose-200 rounded-full flex items-center justify-center mx-auto mb-4 text-rose-600">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <h2 className="text-lg font-bold text-slate-900 mb-2">Error Loading Dashboard</h2>
          <p className="text-slate-600 text-sm mb-6">{error}</p>
          <div className="flex gap-3 justify-center">
            <button 
              onClick={() => window.location.reload()}
              className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-lg text-sm font-semibold transition-all"
            >
              Retry
            </button>
            <button 
              onClick={handleLogout}
              className="px-4 py-2 border border-slate-200 hover:bg-slate-50 text-slate-700 rounded-lg text-sm font-semibold transition-all"
            >
              Sign Out
            </button>
          </div>
        </div>
      </div>
    );
  }

  const { company, rfqs } = dashboardData || {};
  const activeRfqsCount = rfqs?.filter(r => r.status === 'ACTIVE').length || 0;
  const inactiveRfqsCount = rfqs?.filter(r => r.status === 'INACTIVE').length || 0;

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 font-sans selection:bg-blue-100 flex flex-col">
      {/* Top Banner/Navigation */}
      <header className="bg-white border-b border-slate-200/80 sticky top-0 z-30">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <img src={BridgeIcon} alt="VendorBridge" className="h-9 w-auto object-contain" />
            <div>
              <h1 className="text-lg font-black tracking-tight text-slate-900">
                Vendor<span className="text-blue-600">Bridge</span>
              </h1>
              <p className="text-[8px] uppercase tracking-wider text-slate-400 font-black -mt-0.5">Console Portal</p>
            </div>
          </div>

          <div className="flex items-center gap-4">
            <div className="text-right hidden sm:block">
              <span className="text-sm font-bold text-slate-900 block">{company?.name}</span>
              <span className="text-[10px] text-slate-400 font-semibold bg-slate-100 px-2 py-0.5 rounded-full uppercase tracking-wider">{company?.role}</span>
            </div>
            <div className="h-9 w-px bg-slate-200"></div>
            <button 
              onClick={handleLogout}
              className="px-4 py-2 rounded-lg bg-rose-50 text-rose-600 hover:bg-rose-100/80 text-xs font-bold transition-all duration-200 flex items-center gap-1.5 cursor-pointer"
            >
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
              </svg>
              Sign Out
            </button>
          </div>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="max-w-7xl mx-auto px-6 py-8 flex-1 w-full space-y-8">
        
        {/* Profile Card & Info */}
        <section className="bg-gradient-to-r from-slate-900 via-slate-800 to-blue-950 text-white rounded-3xl p-6 md:p-8 shadow-sm flex flex-col md:flex-row justify-between items-start md:items-center gap-6 relative overflow-hidden border border-slate-800">
          <div className="absolute inset-0 bg-blue-600/5 mix-blend-color-dodge blur-2xl pointer-events-none" />
          
          <div className="space-y-2 relative z-10">
            <span className="text-[10px] uppercase bg-blue-600 text-blue-50 px-2.5 py-1 rounded-md font-bold tracking-wider">Enterprise Tenant</span>
            <h2 className="text-2xl md:text-3xl font-black tracking-tight">{company?.name}</h2>
            <p className="text-slate-300 text-sm max-w-xl font-normal leading-relaxed">{company?.description || "A registered corporate business workspace managing procurement loops."}</p>
          </div>

          <div className="grid grid-cols-2 gap-x-8 gap-y-3 bg-white/5 border border-white/10 p-4 rounded-2xl text-xs relative z-10 w-full md:w-auto min-w-[280px]">
            <div>
              <span className="text-slate-400 font-semibold block uppercase tracking-wider text-[9px]">Country</span>
              <span className="font-bold text-slate-100">{company?.country || "N/A"}</span>
            </div>
            <div>
              <span className="text-slate-400 font-semibold block uppercase tracking-wider text-[9px]">Contact No</span>
              <span className="font-bold text-slate-100">{company?.contactNo || "N/A"}</span>
            </div>
            <div className="col-span-2 border-t border-white/10 pt-2">
              <span className="text-slate-400 font-semibold block uppercase tracking-wider text-[9px]">Official Email</span>
              <span className="font-bold text-slate-100 font-mono break-all">{company?.email}</span>
            </div>
          </div>
        </section>

        {/* Operational Statistics */}
        <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="bg-white border border-slate-200/80 p-5 rounded-2xl shadow-xs">
            <span className="text-[10px] text-slate-400 font-bold block uppercase tracking-wider">Total RFQs</span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-2xl font-black font-mono text-slate-900">{rfqs?.length || 0}</span>
              <span className="text-[10px] text-slate-400 font-medium">issued</span>
            </div>
          </div>
          <div className="bg-white border border-slate-200/80 p-5 rounded-2xl shadow-xs">
            <span className="text-[10px] text-blue-600 font-bold block uppercase tracking-wider">Active RFQs</span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-2xl font-black font-mono text-blue-600">{activeRfqsCount}</span>
              <span className="text-[10px] text-blue-400 font-medium">live bidding</span>
            </div>
          </div>
          <div className="bg-white border border-slate-200/80 p-5 rounded-2xl shadow-xs">
            <span className="text-[10px] text-amber-700 font-bold block uppercase tracking-wider">Expired RFQs</span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-2xl font-black font-mono text-amber-700">{inactiveRfqsCount}</span>
              <span className="text-[10px] text-amber-500 font-medium">inactive</span>
            </div>
          </div>
          <div className="bg-white border border-slate-200/80 p-5 rounded-2xl shadow-xs">
            <span className="text-[10px] text-slate-400 font-bold block uppercase tracking-wider">Team Capacity</span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-2xl font-black font-mono text-slate-900">{(company?.PO?.length || 0) + (company?.manager ? 1 : 0)}</span>
              <span className="text-[10px] text-slate-400 font-medium">officers</span>
            </div>
          </div>
        </section>

        {/* Tab System */}
        <section className="space-y-6">
          <div className="flex border-b border-slate-200">
            <button
              onClick={() => setActiveTab('overview')}
              className={`px-6 py-3 font-bold text-sm border-b-2 transition-all flex items-center gap-2 cursor-pointer ${activeTab === 'overview' ? 'border-blue-600 text-blue-600' : 'border-transparent text-slate-500 hover:text-slate-800'}`}
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
              </svg>
              Overview
            </button>
            <button
              onClick={() => setActiveTab('rfqs')}
              className={`px-6 py-3 font-bold text-sm border-b-2 transition-all flex items-center gap-2 cursor-pointer ${activeTab === 'rfqs' ? 'border-blue-600 text-blue-600' : 'border-transparent text-slate-500 hover:text-slate-800'}`}
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              RFQs Ledger ({rfqs?.length || 0})
            </button>
            <button
              onClick={() => setActiveTab('team')}
              className={`px-6 py-3 font-bold text-sm border-b-2 transition-all flex items-center gap-2 cursor-pointer ${activeTab === 'team' ? 'border-blue-600 text-blue-600' : 'border-transparent text-slate-500 hover:text-slate-800'}`}
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
              </svg>
              Management & POs ({(company?.PO?.length || 0) + (company?.manager ? 1 : 0)})
            </button>
          </div>

          {/* TAB 1: OVERVIEW */}
          {activeTab === 'overview' && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              
              {/* Left Column: Manager Card & Capacity */}
              <div className="lg:col-span-1 space-y-6">
                
                {/* Manager Card */}
                <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-xs space-y-4">
                  <div className="flex justify-between items-center pb-3 border-b border-slate-100">
                    <h3 className="font-bold text-sm text-slate-900">Appointed Manager</h3>
                    <span className="text-[10px] bg-blue-50 text-blue-700 font-bold px-2 py-0.5 rounded uppercase tracking-wider">MANAGER</span>
                  </div>
                  {company?.manager ? (
                    <div className="space-y-3">
                      <div>
                        <span className="text-[9px] text-slate-400 font-semibold block uppercase tracking-wider">Full Name</span>
                        <p className="text-sm font-bold text-slate-900">{company.manager.name}</p>
                      </div>
                      <div>
                        <span className="text-[9px] text-slate-400 font-semibold block uppercase tracking-wider">Email Address</span>
                        <p className="text-xs font-mono font-bold text-slate-600 break-all">{company.manager.email}</p>
                      </div>
                      <div>
                        <span className="text-[9px] text-slate-400 font-semibold block uppercase tracking-wider">Contact No</span>
                        <p className="text-sm font-semibold text-slate-900">{company.manager.contactNo || "N/A"}</p>
                      </div>
                    </div>
                  ) : (
                    <div className="py-6 text-center text-slate-400 space-y-2">
                      <div className="w-10 h-10 rounded-full border border-slate-200 flex items-center justify-center mx-auto text-slate-300">🏢</div>
                      <p className="text-xs font-semibold text-slate-500">No Manager registered yet.</p>
                      <p className="text-[10px] text-slate-400 max-w-[200px] mx-auto leading-normal">Managers register through the portal lookup linking this company.</p>
                    </div>
                  )}
                </div>

                {/* Staff Summary */}
                <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-xs space-y-3">
                  <h3 className="font-bold text-sm text-slate-900 pb-2 border-b border-slate-100">System Capacity</h3>
                  <div className="flex justify-between items-center text-xs">
                    <span className="text-slate-500 font-medium">Managers Assigned</span>
                    <span className="font-bold text-slate-950 font-mono">{company?.manager ? "1" : "0"} / 1</span>
                  </div>
                  <div className="flex justify-between items-center text-xs">
                    <span className="text-slate-500 font-medium">Purchase Officers</span>
                    <span className="font-bold text-slate-950 font-mono">{company?.PO?.length || 0} Active</span>
                  </div>
                </div>

              </div>

              {/* Right Column: Recent RFQs list */}
              <div className="lg:col-span-2 space-y-6">
                <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-xs space-y-4">
                  <div className="flex justify-between items-center pb-3 border-b border-slate-100">
                    <h3 className="font-bold text-sm text-slate-900">Recent RFQ Submissions</h3>
                    <button 
                      onClick={() => setActiveTab('rfqs')}
                      className="text-xs text-blue-600 font-bold hover:underline cursor-pointer"
                    >
                      View All &rarr;
                    </button>
                  </div>

                  {rfqs && rfqs.length > 0 ? (
                    <div className="divide-y divide-slate-100">
                      {rfqs.slice(0, 4).map((rfq, idx) => (
                        <div key={idx} className="py-3.5 flex justify-between items-start gap-4 first:pt-0 last:pb-0">
                          <div className="space-y-1">
                            <h4 className="font-bold text-slate-900 text-sm">{rfq.title}</h4>
                            <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate-500">
                              <span className="flex items-center gap-1">
                                <span className="w-1.5 h-1.5 bg-slate-400 rounded-full" />
                                PO: {rfq.createdBy?.name || "Deleted Staff"}
                              </span>
                              <span className="flex items-center gap-1">
                                <span className="w-1.5 h-1.5 bg-slate-400 rounded-full" />
                                Deadline: {new Date(rfq.deadline).toLocaleDateString()}
                              </span>
                            </div>
                          </div>
                          
                          <div className="text-right flex flex-col items-end gap-1.5">
                            <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider border ${
                              rfq.status === 'ACTIVE' 
                                ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
                                : rfq.status === 'INACTIVE'
                                ? 'bg-amber-50 text-amber-700 border-amber-200'
                                : 'bg-slate-50 text-slate-600 border-slate-200'
                            }`}>
                              {rfq.status}
                            </span>
                            <span className="text-[10px] text-slate-400 font-medium font-mono">{rfq.items?.length || 0} items</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="py-12 text-center text-slate-400 space-y-2">
                      <div className="w-12 h-12 rounded-full border border-slate-200 flex items-center justify-center mx-auto text-slate-300">📄</div>
                      <p className="text-xs font-semibold text-slate-500">No RFQs created yet.</p>
                      <p className="text-[10px] text-slate-400 max-w-[240px] mx-auto leading-normal">Your Purchase Officers will create RFQs to send out to Vendors.</p>
                    </div>
                  )}
                </div>
              </div>

            </div>
          )}

          {/* TAB 2: RFQS LEDGER */}
          {activeTab === 'rfqs' && (
            <div className="bg-white border border-slate-200/80 rounded-2xl shadow-xs overflow-hidden">
              <div className="px-5 py-4 border-b border-slate-100 bg-slate-50/50 flex justify-between items-center">
                <h3 className="font-bold text-sm text-slate-900">RFQ Operations Matrix</h3>
                <div className="flex items-center gap-3">
                  <span className="text-[10px] text-slate-400 font-mono font-bold">{rfqs?.length || 0} records</span>
                  <Link
                    to="/rfq/create"
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold transition-colors shadow-sm shadow-blue-600/20"
                  >
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
                    </svg>
                    Create RFQ
                  </Link>
                </div>
              </div>

              {rfqs && rfqs.length > 0 ? (
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="border-b border-slate-100 text-[10px] text-slate-400 font-black uppercase tracking-wider bg-slate-50/20">
                        <th className="py-3.5 px-5">RFQ Title</th>
                        <th className="py-3.5 px-5">Created By</th>
                        <th className="py-3.5 px-5">Deadline</th>
                        <th className="py-3.5 px-5">Assigned Vendors</th>
                        <th className="py-3.5 px-5">Items</th>
                        <th className="py-3.5 px-5 text-right">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 text-xs">
                      {rfqs.map((rfq, idx) => (
                        <tr key={idx} className="hover:bg-slate-50/40 transition-colors">
                          <td className="py-4 px-5">
                            <span className="font-bold text-slate-900 block">{rfq.title}</span>
                            <span className="text-[10px] text-slate-400 truncate block max-w-xs">{rfq.description || "No description provided"}</span>
                          </td>
                          <td className="py-4 px-5">
                            <span className="font-semibold text-slate-800 block">{rfq.createdBy?.name || "Deleted PO"}</span>
                            <span className="text-[9px] text-slate-400 font-mono block">{rfq.createdBy?.email}</span>
                          </td>
                          <td className="py-4 px-5">
                            <span className="font-semibold text-slate-800 block">{new Date(rfq.deadline).toLocaleDateString()}</span>
                            <span className="text-[9px] text-slate-400 font-mono block">{new Date(rfq.deadline).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                          </td>
                          <td className="py-4 px-5">
                            <div className="flex flex-col gap-1">
                              <span className="font-bold text-slate-800 font-mono bg-slate-100 px-2 py-0.5 rounded w-fit">{rfq.assignedVendors?.length || 0} Vendors</span>
                              <div className="flex flex-wrap gap-1 max-w-xs">
                                {rfq.assignedVendors?.slice(0, 3).map((v, i) => (
                                  <span key={i} className="text-[9px] text-slate-500 bg-slate-50 px-1 border border-slate-200 rounded">{v.name}</span>
                                ))}
                                {rfq.assignedVendors?.length > 3 && (
                                  <span className="text-[9px] text-slate-400 font-mono">+{rfq.assignedVendors.length - 3} more</span>
                                )}
                              </div>
                            </div>
                          </td>
                          <td className="py-4 px-5 font-bold font-mono text-slate-800">
                            {rfq.items?.length || 0}
                          </td>
                          <td className="py-4 px-5 text-right">
                            <span className={`px-2.5 py-1 rounded text-[10px] font-bold uppercase tracking-wider border ${
                              rfq.status === 'ACTIVE' 
                                ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
                                : rfq.status === 'INACTIVE'
                                ? 'bg-amber-50 text-amber-700 border-amber-200'
                                : 'bg-slate-50 text-slate-600 border-slate-200'
                            }`}>
                              {rfq.status}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <div className="py-16 text-center text-slate-400 space-y-2">
                  <div className="w-12 h-12 rounded-full border border-slate-200 flex items-center justify-center mx-auto text-slate-300">📄</div>
                  <p className="text-xs font-semibold text-slate-500">No RFQs created yet.</p>
                </div>
              )}
            </div>
          )}

          {/* TAB 3: TEAM MEMBERS */}
          {activeTab === 'team' && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              
              {/* Manager Details Grid */}
              <div className="lg:col-span-1 space-y-6">
                <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-xs space-y-4">
                  <div className="flex justify-between items-center pb-3 border-b border-slate-100">
                    <h3 className="font-bold text-sm text-slate-900 font-sans">Appointed Manager</h3>
                    <span className="text-[9px] bg-indigo-50 text-indigo-700 font-bold px-2 py-0.5 rounded tracking-wider">MANAGER</span>
                  </div>
                  {company?.manager ? (
                    <div className="space-y-4 text-xs">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-indigo-50 border border-indigo-100 rounded-xl flex items-center justify-center font-bold text-indigo-600 text-sm">
                          {company.manager.name?.charAt(0).toUpperCase()}
                        </div>
                        <div>
                          <p className="font-bold text-slate-900 text-sm">{company.manager.name}</p>
                          <p className="text-[10px] text-slate-400 font-medium">Link: Company Executive Manager</p>
                        </div>
                      </div>
                      <div className="space-y-3 pt-3 border-t border-slate-100">
                        <div>
                          <span className="text-[9px] text-slate-400 font-semibold block uppercase tracking-wider">Email</span>
                          <p className="font-bold text-slate-700 font-mono break-all">{company.manager.email}</p>
                        </div>
                        <div>
                          <span className="text-[9px] text-slate-400 font-semibold block uppercase tracking-wider">Contact No</span>
                          <p className="font-bold text-slate-700">{company.manager.contactNo || "N/A"}</p>
                        </div>
                        <div>
                          <span className="text-[9px] text-slate-400 font-semibold block uppercase tracking-wider">Appointed Date</span>
                          <p className="font-semibold text-slate-700">{company.manager.createdAt ? new Date(company.manager.createdAt).toLocaleDateString() : "N/A"}</p>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="py-12 text-center text-slate-400 space-y-2">
                      <div className="w-10 h-10 rounded-full border border-slate-200 flex items-center justify-center mx-auto text-slate-300">🏢</div>
                      <p className="text-xs font-semibold text-slate-500 text-center">No Manager assigned.</p>
                    </div>
                  )}
                </div>
              </div>

              {/* Purchase Officers Table Grid */}
              <div className="lg:col-span-2 space-y-6">
                <div className="bg-white border border-slate-200/80 rounded-2xl shadow-xs overflow-hidden">
                  <div className="px-5 py-4 border-b border-slate-100 bg-slate-50/50 flex justify-between items-center">
                    <h3 className="font-bold text-sm text-slate-900">Purchase Officers (PO)</h3>
                    <span className="text-[10px] text-slate-400 font-mono font-bold">{company?.PO?.length || 0} officers</span>
                  </div>

                  {company?.PO && company.PO.length > 0 ? (
                    <div className="overflow-x-auto">
                      <table className="w-full text-left border-collapse">
                        <thead>
                          <tr className="border-b border-slate-100 text-[10px] text-slate-400 font-black uppercase tracking-wider bg-slate-50/20">
                            <th className="py-3 px-5">Officer Details</th>
                            <th className="py-3 px-5">Contact Details</th>
                            <th className="py-3 px-5">Appointed Date</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100 text-xs">
                          {company.PO.map((po, idx) => (
                            <tr key={idx} className="hover:bg-slate-50/40 transition-colors">
                              <td className="py-3.5 px-5">
                                <div className="flex items-center gap-2.5">
                                  <div className="w-7 h-7 bg-blue-50 border border-blue-100 rounded-lg flex items-center justify-center font-bold text-blue-600 text-xs uppercase">
                                    {po.name?.charAt(0)}
                                  </div>
                                  <div>
                                    <span className="font-bold text-slate-900 block">{po.name}</span>
                                    <span className="text-[10px] text-slate-400 bg-blue-50 border border-blue-100 px-1.5 py-0.2 rounded w-fit uppercase font-semibold">PO</span>
                                  </div>
                                </div>
                              </td>
                              <td className="py-3.5 px-5">
                                <span className="font-mono text-slate-700 block">{po.email}</span>
                                <span className="text-[10px] text-slate-400 block">{po.contactNo || "N/A"}</span>
                              </td>
                              <td className="py-3.5 px-5 font-semibold text-slate-600 font-mono">
                                {po.createdAt ? new Date(po.createdAt).toLocaleDateString() : "N/A"}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  ) : (
                    <div className="py-16 text-center text-slate-400 space-y-2">
                      <div className="w-12 h-12 rounded-full border border-slate-200 flex items-center justify-center mx-auto text-slate-300">👥</div>
                      <p className="text-xs font-semibold text-slate-500">No Purchase Officers registered yet.</p>
                      <p className="text-[10px] text-slate-400 max-w-[280px] mx-auto leading-normal">Purchase Officers join by linking this company during portal registration.</p>
                    </div>
                  )}
                </div>
              </div>

            </div>
          )}

        </section>

      </main>

      {/* Footer */}
      <footer className="max-w-7xl mx-auto px-6 py-8 text-center text-slate-400 text-[10px] w-full border-t border-slate-200 mt-auto">
        <p>&copy; 2026 VendorBridge Procurement Enterprise Workspace. Portal Console Node. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default CompanyPage;
